"""correccion de resultado

Revision ID: 005783ca4fd4
Revises: 5c495189c3a8
Create Date: 2026-08-13 19:15:35.997330

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '005783ca4fd4'
down_revision: Union[str, Sequence[str], None] = '5c495189c3a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reportes_resultado', schema=None) as batch_op:
        # server_default agregado a mano: sin esto, aplicar esta migración
        # sobre una tabla con filas existentes falla (NOT NULL sin default).
        # Autogenerate no lo agrega solo — hay que revisarlo siempre.
        batch_op.add_column(sa.Column('es_correccion', sa.Boolean(), nullable=False, server_default=sa.false()))
        batch_op.add_column(sa.Column('motivo', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('aplicado_por_usuario_id', sa.Integer(), nullable=True))
        batch_op.alter_column('equipo_reportante_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        # SQLite en modo batch (recrea la tabla) exige que la FK tenga
        # nombre explícito -- autogenerate la deja sin nombre y eso falla
        # acá aunque en Postgres no haría falta. Otra cosa que autogenerate
        # no resuelve sola.
        batch_op.create_foreign_key(
            'fk_reportes_resultado_aplicado_por_usuario_id',
            'usuarios', ['aplicado_por_usuario_id'], ['id'],
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reportes_resultado', schema=None) as batch_op:
        batch_op.drop_constraint('fk_reportes_resultado_aplicado_por_usuario_id', type_='foreignkey')
        batch_op.alter_column('equipo_reportante_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('aplicado_por_usuario_id')
        batch_op.drop_column('motivo')
        batch_op.drop_column('es_correccion')

    # ### end Alembic commands ###
