"""segundo nivel de permiso para organizadores

Revision ID: 41f82b35faa7
Revises: 005783ca4fd4
Create Date: 2026-08-13 19:39:34.372812

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '41f82b35faa7'
down_revision: Union[str, Sequence[str], None] = '005783ca4fd4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        # server_default agregado a mano, autogenerate no lo pone solo.
        batch_op.add_column(
            sa.Column(
                'puede_gestionar_organizadores', sa.Boolean(),
                nullable=False, server_default=sa.false(),
            )
        )
    # ### end Alembic commands ###

    # Ajuste de datos, agregado a mano — esto NO lo genera autogenerate:
    # quien ya era organizador ANTES de que existiera este segundo nivel
    # tiene que conservar el permiso completo. Si todos entraran con
    # False por defecto, un despliegue de esto dejaría a la plataforma
    # sin NADIE que pueda gestionar organizadores — ni siquiera vos.
    op.execute(
        "UPDATE usuarios SET puede_gestionar_organizadores = true "
        "WHERE es_organizador = true"
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_column('puede_gestionar_organizadores')

    # ### end Alembic commands ###
