"""esquema inicial

Revision ID: 5c495189c3a8
Revises: 
Create Date: 2026-08-13 16:18:17.383894

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import app.db.database  # necesario para el tipo DateTimeUTC usado abajo


# revision identifiers, used by Alembic.
revision: str = '5c495189c3a8'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('equipos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('tag', sa.String(length=12), nullable=True),
    sa.Column('logo_url', sa.String(length=500), nullable=True),
    sa.Column('contacto_nombre', sa.String(length=120), nullable=True),
    sa.Column('contacto_whatsapp', sa.String(length=40), nullable=True),
    sa.Column('contacto_discord', sa.String(length=80), nullable=True),
    sa.Column('esta_activo', sa.Boolean(), nullable=False),
    sa.Column('created_at', app.db.database.DateTimeUTC(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('equipos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_equipos_nombre'), ['nombre'], unique=False)

    op.create_table('juegos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=40), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('modelo_competencia_default', sa.Enum('ENFRENTAMIENTO_DIRECTO', 'MULTI_EQUIPO', name='modelocompetencia', native_enum=False, length=40), nullable=False),
    sa.Column('titulares_requeridos', sa.Integer(), nullable=False),
    sa.Column('suplentes_maximos', sa.Integer(), nullable=False),
    sa.Column('campos_identidad', sa.JSON(), nullable=False),
    sa.Column('esta_activo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('juegos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_juegos_codigo'), ['codigo'], unique=True)

    op.create_table('torneos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=160), nullable=False),
    sa.Column('slug', sa.String(length=160), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('logo_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', app.db.database.DateTimeUTC(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('torneos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_torneos_slug'), ['slug'], unique=True)

    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('discord_id', sa.String(length=40), nullable=False),
    sa.Column('discord_username', sa.String(length=120), nullable=False),
    sa.Column('discord_avatar_url', sa.String(length=500), nullable=True),
    sa.Column('es_organizador', sa.Boolean(), nullable=False),
    sa.Column('esta_activo', sa.Boolean(), nullable=False),
    sa.Column('created_at', app.db.database.DateTimeUTC(timezone=True), nullable=False),
    sa.Column('ultimo_login_at', app.db.database.DateTimeUTC(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_usuarios_discord_id'), ['discord_id'], unique=True)

    op.create_table('ediciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('torneo_id', sa.Integer(), nullable=False),
    sa.Column('juego_id', sa.Integer(), nullable=False),
    sa.Column('numero', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=160), nullable=False),
    sa.Column('slug', sa.String(length=180), nullable=False),
    sa.Column('estado', sa.Enum('BORRADOR', 'INSCRIPCIONES_ABIERTAS', 'INSCRIPCIONES_CERRADAS', 'EN_CURSO', 'FINALIZADA', 'CANCELADA', name='estadoedicion', native_enum=False, length=40), nullable=False),
    sa.Column('zona_horaria', sa.String(length=60), nullable=False),
    sa.Column('max_equipos', sa.Integer(), nullable=True),
    sa.Column('inscripcion_abre', app.db.database.DateTimeUTC(timezone=True), nullable=True),
    sa.Column('inscripcion_cierra', app.db.database.DateTimeUTC(timezone=True), nullable=True),
    sa.Column('roster_lock', app.db.database.DateTimeUTC(timezone=True), nullable=True),
    sa.Column('reglamento_url', sa.String(length=500), nullable=True),
    sa.Column('version_reglamento', sa.String(length=40), nullable=True),
    sa.Column('sistema_puntaje', sa.JSON(), nullable=False),
    sa.Column('criterios_desempate', sa.JSON(), nullable=False),
    sa.Column('created_at', app.db.database.DateTimeUTC(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['juego_id'], ['juegos.id'], ),
    sa.ForeignKeyConstraint(['torneo_id'], ['torneos.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('torneo_id', 'numero', name='uq_edicion_numero')
    )
    with op.batch_alter_table('ediciones', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ediciones_estado'), ['estado'], unique=False)
        batch_op.create_index(batch_op.f('ix_ediciones_juego_id'), ['juego_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ediciones_slug'), ['slug'], unique=True)
        batch_op.create_index(batch_op.f('ix_ediciones_torneo_id'), ['torneo_id'], unique=False)

    op.create_table('fases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('edicion_id', sa.Integer(), nullable=False),
    sa.Column('orden', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('modelo_competencia', sa.Enum('ENFRENTAMIENTO_DIRECTO', 'MULTI_EQUIPO', name='modelocompetencia', native_enum=False, length=40), nullable=False),
    sa.Column('formato', sa.Enum('ROUND_ROBIN', 'ELIMINACION_SIMPLE', 'ELIMINACION_DOBLE', 'SUIZO', 'LIGA_ACUMULATIVA', name='formatofase', native_enum=False, length=40), nullable=False),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('estado', sa.String(length=40), nullable=False),
    sa.Column('semilla_sorteo', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['edicion_id'], ['ediciones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('fases', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fases_edicion_id'), ['edicion_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_fases_estado'), ['estado'], unique=False)

    op.create_table('inscripciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('edicion_id', sa.Integer(), nullable=False),
    sa.Column('equipo_id', sa.Integer(), nullable=False),
    sa.Column('estado', sa.Enum('PENDIENTE', 'APROBADA', 'RECHAZADA', 'RETIRADA', 'DESCALIFICADA', name='estadoinscripcion', native_enum=False, length=40), nullable=False),
    sa.Column('motivo_rechazo', sa.Text(), nullable=True),
    sa.Column('seed', sa.Integer(), nullable=True),
    sa.Column('created_at', app.db.database.DateTimeUTC(timezone=True), nullable=False),
    sa.Column('revisada_at', app.db.database.DateTimeUTC(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['edicion_id'], ['ediciones.id'], ),
    sa.ForeignKeyConstraint(['equipo_id'], ['equipos.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('edicion_id', 'equipo_id', name='uq_inscripcion_equipo')
    )
    with op.batch_alter_table('inscripciones', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_inscripciones_edicion_id'), ['edicion_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_inscripciones_equipo_id'), ['equipo_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_inscripciones_estado'), ['estado'], unique=False)

    op.create_table('jugadores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('inscripcion_id', sa.Integer(), nullable=False),
    sa.Column('edicion_id', sa.Integer(), nullable=False),
    sa.Column('identidad', sa.JSON(), nullable=False),
    sa.Column('clave_identidad', sa.String(length=200), nullable=False),
    sa.Column('orden', sa.Integer(), nullable=False),
    sa.Column('es_suplente', sa.Boolean(), nullable=False),
    sa.Column('es_capitan', sa.Boolean(), nullable=False),
    sa.Column('discord_id', sa.String(length=40), nullable=True),
    sa.ForeignKeyConstraint(['edicion_id'], ['ediciones.id'], ),
    sa.ForeignKeyConstraint(['inscripcion_id'], ['inscripciones.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('edicion_id', 'clave_identidad', name='uq_jugador_elegibilidad')
    )
    with op.batch_alter_table('jugadores', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_jugadores_clave_identidad'), ['clave_identidad'], unique=False)
        batch_op.create_index(batch_op.f('ix_jugadores_discord_id'), ['discord_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_jugadores_edicion_id'), ['edicion_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_jugadores_inscripcion_id'), ['inscripcion_id'], unique=False)

    op.create_table('partidas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fase_id', sa.Integer(), nullable=False),
    sa.Column('numero_caida', sa.Integer(), nullable=True),
    sa.Column('lado', sa.Enum('UNICA', 'ALTA', 'BAJA', 'GRAN_FINAL', name='ladollave', native_enum=False, length=20), nullable=False),
    sa.Column('ronda', sa.Integer(), nullable=True),
    sa.Column('grupo_numero', sa.Integer(), nullable=True),
    sa.Column('estado', sa.Enum('PROGRAMADA', 'CHECK_IN', 'EN_CURSO', 'REPORTADA', 'CONFIRMADA', 'EN_DISPUTA', 'WALKOVER', 'BYE', name='estadopartida', native_enum=False, length=40), nullable=False),
    sa.Column('siguiente_partida_ganador_id', sa.Integer(), nullable=True),
    sa.Column('siguiente_slot_ganador', sa.Integer(), nullable=True),
    sa.Column('siguiente_partida_perdedor_id', sa.Integer(), nullable=True),
    sa.Column('siguiente_slot_perdedor', sa.Integer(), nullable=True),
    sa.Column('programada_para', app.db.database.DateTimeUTC(timezone=True), nullable=True),
    sa.Column('checkin_abre_at', app.db.database.DateTimeUTC(timezone=True), nullable=True),
    sa.Column('checkin_cierra_at', app.db.database.DateTimeUTC(timezone=True), nullable=True),
    sa.Column('confirmada_at', app.db.database.DateTimeUTC(timezone=True), nullable=True),
    sa.Column('created_at', app.db.database.DateTimeUTC(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['fase_id'], ['fases.id'], ),
    sa.ForeignKeyConstraint(['siguiente_partida_ganador_id'], ['partidas.id'], ),
    sa.ForeignKeyConstraint(['siguiente_partida_perdedor_id'], ['partidas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('partidas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_partidas_estado'), ['estado'], unique=False)
        batch_op.create_index(batch_op.f('ix_partidas_fase_id'), ['fase_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_partidas_grupo_numero'), ['grupo_numero'], unique=False)

    op.create_table('disputas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('partida_id', sa.Integer(), nullable=False),
    sa.Column('abierta_por_equipo_id', sa.Integer(), nullable=False),
    sa.Column('motivo', sa.Text(), nullable=False),
    sa.Column('evidencia_url', sa.String(length=500), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('resolucion', sa.Text(), nullable=True),
    sa.Column('resuelta_at', app.db.database.DateTimeUTC(timezone=True), nullable=True),
    sa.Column('created_at', app.db.database.DateTimeUTC(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['abierta_por_equipo_id'], ['equipos.id'], ),
    sa.ForeignKeyConstraint(['partida_id'], ['partidas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('disputas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_disputas_estado'), ['estado'], unique=False)
        batch_op.create_index(batch_op.f('ix_disputas_partida_id'), ['partida_id'], unique=False)

    op.create_table('participaciones_partida',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('partida_id', sa.Integer(), nullable=False),
    sa.Column('equipo_id', sa.Integer(), nullable=False),
    sa.Column('slot', sa.Integer(), nullable=True),
    sa.Column('mapas_ganados', sa.Integer(), nullable=True),
    sa.Column('es_ganador', sa.Boolean(), nullable=True),
    sa.Column('posicion', sa.Integer(), nullable=True),
    sa.Column('bajas', sa.Integer(), nullable=True),
    sa.Column('puntos', sa.Integer(), nullable=True),
    sa.Column('checkin_at', app.db.database.DateTimeUTC(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['equipo_id'], ['equipos.id'], ),
    sa.ForeignKeyConstraint(['partida_id'], ['partidas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('partida_id', 'equipo_id', name='uq_participacion_equipo')
    )
    with op.batch_alter_table('participaciones_partida', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_participaciones_partida_equipo_id'), ['equipo_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_participaciones_partida_partida_id'), ['partida_id'], unique=False)

    op.create_table('reportes_resultado',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('partida_id', sa.Integer(), nullable=False),
    sa.Column('equipo_reportante_id', sa.Integer(), nullable=False),
    sa.Column('marcador_propio', sa.Integer(), nullable=False),
    sa.Column('marcador_rival', sa.Integer(), nullable=False),
    sa.Column('evidencia_url', sa.String(length=500), nullable=True),
    sa.Column('estado', sa.String(length=30), nullable=False),
    sa.Column('vencimiento', app.db.database.DateTimeUTC(timezone=True), nullable=True),
    sa.Column('confirmado_por_equipo_id', sa.Integer(), nullable=True),
    sa.Column('confirmado_at', app.db.database.DateTimeUTC(timezone=True), nullable=True),
    sa.Column('created_at', app.db.database.DateTimeUTC(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['confirmado_por_equipo_id'], ['equipos.id'], ),
    sa.ForeignKeyConstraint(['equipo_reportante_id'], ['equipos.id'], ),
    sa.ForeignKeyConstraint(['partida_id'], ['partidas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('reportes_resultado', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reportes_resultado_estado'), ['estado'], unique=False)
        batch_op.create_index(batch_op.f('ix_reportes_resultado_partida_id'), ['partida_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reportes_resultado', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reportes_resultado_partida_id'))
        batch_op.drop_index(batch_op.f('ix_reportes_resultado_estado'))

    op.drop_table('reportes_resultado')
    with op.batch_alter_table('participaciones_partida', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_participaciones_partida_partida_id'))
        batch_op.drop_index(batch_op.f('ix_participaciones_partida_equipo_id'))

    op.drop_table('participaciones_partida')
    with op.batch_alter_table('disputas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_disputas_partida_id'))
        batch_op.drop_index(batch_op.f('ix_disputas_estado'))

    op.drop_table('disputas')
    with op.batch_alter_table('partidas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_partidas_grupo_numero'))
        batch_op.drop_index(batch_op.f('ix_partidas_fase_id'))
        batch_op.drop_index(batch_op.f('ix_partidas_estado'))

    op.drop_table('partidas')
    with op.batch_alter_table('jugadores', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_jugadores_inscripcion_id'))
        batch_op.drop_index(batch_op.f('ix_jugadores_edicion_id'))
        batch_op.drop_index(batch_op.f('ix_jugadores_discord_id'))
        batch_op.drop_index(batch_op.f('ix_jugadores_clave_identidad'))

    op.drop_table('jugadores')
    with op.batch_alter_table('inscripciones', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_inscripciones_estado'))
        batch_op.drop_index(batch_op.f('ix_inscripciones_equipo_id'))
        batch_op.drop_index(batch_op.f('ix_inscripciones_edicion_id'))

    op.drop_table('inscripciones')
    with op.batch_alter_table('fases', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fases_estado'))
        batch_op.drop_index(batch_op.f('ix_fases_edicion_id'))

    op.drop_table('fases')
    with op.batch_alter_table('ediciones', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ediciones_torneo_id'))
        batch_op.drop_index(batch_op.f('ix_ediciones_slug'))
        batch_op.drop_index(batch_op.f('ix_ediciones_juego_id'))
        batch_op.drop_index(batch_op.f('ix_ediciones_estado'))

    op.drop_table('ediciones')
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_usuarios_discord_id'))

    op.drop_table('usuarios')
    with op.batch_alter_table('torneos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_torneos_slug'))

    op.drop_table('torneos')
    with op.batch_alter_table('juegos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_juegos_codigo'))

    op.drop_table('juegos')
    with op.batch_alter_table('equipos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_equipos_nombre'))

    op.drop_table('equipos')
    # ### end Alembic commands ###
